[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  name = "github.com/vmware/govmomi"
  version = "0.17.1"

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.7.0"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.0"
